### ISSUE TITLE
No code is shown

### ISSUE THREAD

**Issue by hbtholen** [jaazi20/Crypto-Price-Prediction-with-Binance-API-using-RandomForest-Regressor-#1]
Hi there,
I'm interested in your code for educational use, but nothing is shown.

**Comment by jaazi20** [comment]
Hello Mater,

I’ll share my code to you and will explain to you kindly share your information with me

Thanks

Sent from my iPhone

On Jun 13, 2022, at 12:12 AM, hbtholen ***@***.***> wrote:

﻿

Hi there,
I'm interested in your code for educational use, but nothing is shown.
